package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/online-shop/services/identity/internal/adapters/inbound/graphql/model"
	"github.com/online-shop/services/identity/internal/app/ports"
)

// FindUserByID resolves a User entity reference for another subgraph (federation
// boilerplate). Unused until a subgraph extends User, but correct when it does:
// entity resolution is router-internal and trusted, so it carries no per-user
// authorization of its own.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	ctx, span := tracer.Start(ctx, "identity.getuser")
	defer span.End()

	got, err := r.userGetter.Execute(ctx, ports.GetUserRequest{UserID: id})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toUserModel(got.User), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
