package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/online-shop/services/identity/internal/adapters/inbound/graphql/model"
	"github.com/online-shop/services/identity/internal/app/ports"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterUserInput) (*model.User, error) {
	ctx, span := tracer.Start(ctx, "identity.registeruser")
	defer span.End()

	reg, err := r.registrar.Execute(ctx, ports.RegisterUserRequest{Email: input.Email, Password: input.Password})
	if err != nil {
		return nil, toGraphQLError(err)
	}

	// Read the user back so the returned entity is fully populated (roles,
	// createdAt) without widening the register use case's response DTO.
	got, err := r.userGetter.Execute(ctx, ports.GetUserRequest{UserID: reg.UserID})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toUserModel(got.User), nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input model.LoginUserInput) (*model.AuthPayload, error) {
	ctx, span := tracer.Start(ctx, "identity.loginuser")
	defer span.End()

	resp, err := r.authenticator.Execute(ctx, ports.LoginUserRequest{Email: input.Email, Password: input.Password})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toAuthPayloadModel(resp), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// The router validates the JWT at the edge and forwards the principal as
	// headers; no caller means the request arrived without one ⇒ unauthenticated.
	c, ok := callerFromContext(ctx)
	if !ok {
		return nil, toGraphQLError(errUnauthenticated)
	}

	ctx, span := tracer.Start(ctx, "identity.getuser")
	defer span.End()

	got, err := r.userGetter.Execute(ctx, ports.GetUserRequest{UserID: c.userID})
	if err != nil {
		return nil, toGraphQLError(err)
	}
	return toUserModel(got.User), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
